using Kkdev92.HealthData.CodeGen.IntermediateModel;
using Kkdev92.HealthData.CodeGen.Specifications;

namespace Kkdev92.HealthData.CodeGen.CSharp;

internal sealed record GeneratedFile(string RelativePath, string Content);

/// <summary>
/// Renders the normalized IR as C# source.
/// </summary>
/// <remarks>
/// The emitter never sees the Discovery document; everything it
/// needs has already been resolved into <see cref="ApiContract"/>.
/// </remarks>
internal sealed class CSharpEmitter(
    ApiContract contract,
    IReadOnlySet<string>? flattenedResourcePaths = null,
    IReadOnlyDictionary<string, UnionContract>? unions = null)
{
    private const string RootNamespace = "Kkdev92.HealthData";

    /// <summary>
    /// Where a generated type lives, decided by what it is.
    /// </summary>
    /// <remarks>
    /// A Discovery schema - something that crosses the wire - goes to <c>.Models</c>, and the
    /// request envelopes this SDK synthesizes go to <c>.Requests</c>. The client, its resources,
    /// the operation table and the scope and error constants stay at the root, so the first thing
    /// a consumer sees when they type the package name is the client rather than 249 alphabetized
    /// wire types. Nested namespaces see the root without a using, so models refer to the wire
    /// primitives freely; the reverse direction is spelled out per file.
    /// </remarks>
    internal const string ModelsNamespace = RootNamespace + ".Models";

    /// <inheritdoc cref="ModelsNamespace"/>
    internal const string RequestsNamespace = RootNamespace + ".Requests";

    private readonly IReadOnlySet<string> _flattenedResourcePaths =
        flattenedResourcePaths ?? new HashSet<string>(StringComparer.Ordinal);

    /// <summary>
    /// Union schemas, each with the message-typed members that are not alternatives.
    /// </summary>
    /// <remarks>
    /// Declared in <c>semantics.json</c> rather than inferred, because Discovery cannot express
    /// "exactly one of these" and the difference is not visible in the schema. Empty means no
    /// union helpers are emitted at all, which is what an unconfigured run should do rather than
    /// guess.
    /// </remarks>
    private readonly IReadOnlyDictionary<string, UnionContract> _unions =
        unions ?? new Dictionary<string, UnionContract>(StringComparer.Ordinal);

    /// <summary>How many reachable schemas were deliberately not emitted.</summary>
    public int SkippedSchemaCount { get; private set; }

    /// <summary>Request type names keyed by operation id, populated by <see cref="Emit"/>.</summary>
    public IReadOnlyDictionary<string, string> RequestTypeNames { get; private set; } =
        new Dictionary<string, string>(StringComparer.Ordinal);

    public IReadOnlyList<GeneratedFile> Emit()
    {
        var files = new List<GeneratedFile>
        {
            EmitApiInfo(),
            EmitScopes(),
            EmitErrorReasons(),
            EmitOperations(),
            EmitJsonContext(),
            EmitOutputOnlyProperties(),
            EmitUnionMembers(),
            EmitDataTypes(),
        };

        files.AddRange(contract.Schemas.Select(EmitModel));

        // One container per owner rather than one file per enum: Settings declares eight, and
        // eight partials of the same class saying the same thing would be noise.
        files.AddRange(contract.OpenEnums
            .GroupBy(e => e.DeclaringSchema, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .Select(EmitOpenEnumContainer));

        foreach (var (unionSchema, declared) in _unions.OrderBy(u => u.Key, StringComparer.Ordinal))
        {
            if (contract.Schemas.SingleOrDefault(s => s.WireName == unionSchema) is { } union)
            {
                files.Add(EmitUnionHelpers(union, declared.ExcludedMembers));
            }
        }

        // The name types come before the requests that use them, so a reader of the generated
        // set meets the type before the property typed with it.
        files.AddRange(new ResourceNameEmitter(contract).Emit(Header));

        var resources = new ResourceEmitter(contract, _flattenedResourcePaths);
        resources.ResolveRequestTypeNames();
        RequestTypeNames = resources.RequestTypeNames;

        files.AddRange(resources.EmitRequests(Header));
        files.AddRange(resources.EmitResources(resources.BuildTree(), Header));

        return files.OrderBy(f => f.RelativePath, StringComparer.Ordinal).ToArray();
    }

    /// <summary>
    /// The provenance header carried by every generated file. It records what the contract came
    /// from and nothing about when or where it was generated.
    /// </summary>
    private CodeWriter Header(string namespaceName, params string[] usings)
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated />");
        writer.Line("// Google Health API contract generated by Kkdev92.HealthData.CodeGen.");
        writer.Line($"// API version: {contract.ApiVersion}");
        writer.Line($"// Discovery revision: {contract.Revision}");
        writer.Line($"// Spec SHA-256: {contract.SpecSha256}");
        writer.Line("//");
        writer.Line("// Doc comments are derived from the Google Health API Discovery document,");
        writer.Line("// (c) Google LLC, licensed under CC BY 4.0. See NOTICE.");
        writer.Line("//");
        writer.Line("// Do not edit by hand. Run 'codegen generate' instead.");
        writer.Line();
        writer.Line("#nullable enable");
        writer.Line();

        // Usings precede the file-scoped namespace, matching the repository style rules
        // (csharp_using_directive_placement = outside_namespace, System directives first).
        if (usings.Length > 0)
        {
            var ordered = usings
                .OrderBy(u => u.StartsWith("System", StringComparison.Ordinal) ? 0 : 1)
                .ThenBy(u => u, StringComparer.Ordinal);

            writer.Lines(ordered.Select(u => $"using {u};"));
            writer.Line();
        }

        writer.Line($"namespace {namespaceName};");
        writer.Line();
        return writer;
    }

    private GeneratedFile EmitApiInfo()
    {
        var writer = Header(RootNamespace);

        writer.XmlDoc("summary", "Identifies the Google Health API contract this assembly was generated from.");
        using (writer.Block("public static class HealthDataGeneratedApi"))
        {
            writer.XmlDoc("summary", "The Google Health API version, for example v4.");
            writer.Line($"public const string ApiVersion = {CodeWriter.Literal(contract.ApiVersion)};");
            writer.Line();

            writer.XmlDoc("summary", "The Discovery document revision this contract was generated from.");
            writer.Line($"public const string DiscoveryRevision = {CodeWriter.Literal(contract.Revision)};");
            writer.Line();

            writer.XmlDoc("summary", "The SHA-256 of the Discovery snapshot, matching spec metadata.json.");
            writer.Line($"public const string SpecSha256 = {CodeWriter.Literal(contract.SpecSha256)};");
            writer.Line();

            writer.XmlDoc("summary", "The number of operations exposed by this contract.");
            writer.Line($"public const int OperationCount = {CodeWriter.Number(contract.Operations.Count)};");
        }

        return new GeneratedFile("Generated/Api/HealthDataGeneratedApi.g.cs", writer.ToString());
    }

    private GeneratedFile EmitScopes()
    {
        var writer = Header(RootNamespace);

        writer.XmlDoc("summary", "OAuth 2.0 scopes declared by the Google Health API.");
        writer.XmlDoc(
            "remarks",
            "Scope values are wire constants. They are never reshaped and never treated as an " +
            "exhaustive set: an operation may start requiring a scope that is not listed here.");
        using (writer.Block("public static class HealthDataScopes"))
        {
            var first = true;

            foreach (var scope in contract.Scopes)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;
                writer.XmlDoc("summary", scope.Description ?? scope.Url);
                writer.Line($"public const string {scope.CSharpName} = {CodeWriter.Literal(scope.Url)};");
            }

            EmitScopeSet(
                writer,
                "All",
                "Every scope this contract declares.",
                "The set an application would present for review, and the one the three below "
                + "partition. Not a promise of completeness about the service: an operation may "
                + "start requiring a scope that is not here.",
                contract.Scopes);

            EmitScopeSet(
                writer,
                "ReadOnly",
                "The scopes that only read a person's data.",
                "For an application that shows data and does not change it. Asking for these and "
                + "nothing else is what keeps the consent screen honest - and what stops a write "
                + "scope arriving because an operation that reads happens to accept one.",
                contract.Scopes.Where(scope => scope.Kind == ScopeKind.Read));

            EmitScopeSet(
                writer,
                "WriteOnly",
                "The scopes that add to, edit, or delete a person's data.",
                "Google's own wording for each of these is \"Add ... and edit or delete the data it "
                + "adds\", which is worth reading before asking for one.",
                contract.Scopes.Where(scope => scope.Kind == ScopeKind.Write));

            EmitScopeSet(
                writer,
                "Project",
                "The scopes that authorize as the project rather than as a person.",
                "cloud-platform, which a consent screen shows as \"see, edit, configure and delete "
                + "your Google Cloud data\". The operations needing it are meant for a service "
                + "account; asking a person for it so an app can list webhook subscribers is not a "
                + "trade worth making.",
                contract.Scopes.Where(scope => scope.Kind == ScopeKind.Project));
        }

        return new GeneratedFile("Generated/Scopes/HealthDataScopes.g.cs", writer.ToString());
    }

    /// <summary>
    /// Emits one named set of scopes.
    /// </summary>
    /// <remarks>
    /// Sets rather than a predicate, because the question a consumer has is "which ones do I ask
    /// for". The classification is declared in <c>semantics.json</c>: an application that worked it
    /// out by matching on <c>".writeonly"</c> was relying on Google's naming, which nothing in this
    /// package promised to keep.
    /// </remarks>
    private static void EmitScopeSet(
        CodeWriter writer,
        string name,
        string summary,
        string remarks,
        IEnumerable<ScopeContract> scopes)
    {
        writer.Line();
        writer.XmlDoc("summary", summary);
        writer.XmlDoc("remarks", remarks);

        // A collection expression rather than a block: Block writes braces, and this is a list.
        writer.Line($"public static IReadOnlyList<string> {name} {{ get; }} =");
        writer.Line("[");

        foreach (var scope in scopes)
        {
            writer.Line($"    {scope.CSharpName},");
        }

        writer.Line("];");
    }

    private GeneratedFile EmitErrorReasons()
    {
        var writer = Header(RootNamespace);

        writer.XmlDoc("summary", "Documented Google Health API error reasons.");
        writer.XmlDoc(
            "remarks",
            "These are constants rather than an enum on purpose (ADR-0005). The service may return " +
            "a reason that is not listed here, and an unknown reason must pass through unchanged.");
        using (writer.Block("public static class HealthDataErrorReasons"))
        {
            var first = true;

            foreach (var reason in contract.ErrorReasons)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;
                writer.XmlDoc("summary", $"HTTP {CodeWriter.Number(reason.HttpStatus)}.");
                writer.Line(
                    $"public const string {NameOf(reason)} = {CodeWriter.Literal(reason.Reason)};");
            }

            writer.Line();
            writer.XmlDoc("summary", "Whether a value is one of the reasons above.");
            writer.XmlDoc(
                "remarks",
                "Emitted from the same list, so it cannot fall behind it. This is what decides "
                + "whether a reason is safe to put in an exception message: the value arrives off "
                + "the wire, and looking at its shape cannot tell a documented reason from a "
                + "secret or a user id that happens to be spelled the same way.");

            var reasons = contract.ErrorReasons.ToArray();

            writer.Line("public static bool IsDocumented(string? reason) => reason is");

            for (var i = 0; i < reasons.Length; i++)
            {
                var literal = CodeWriter.Literal(reasons[i].Reason);
                writer.Line(i == reasons.Length - 1 ? $"    {literal};" : $"    {literal} or");
            }
        }

        return new GeneratedFile("Generated/Errors/HealthDataErrorReasons.g.cs", writer.ToString());

        static string NameOf(ErrorReasonContract reason)
            => Normalization.NamingNormalizer.ErrorReasonConstantName(reason.Reason);
    }

    /// <summary>
    /// Emits the operation metadata table.
    /// </summary>
    /// <remarks>
    /// One descriptor per operation, carrying the path template, scopes, credential kind, retry
    /// classification, response kind and pagination. Each is attached to the outgoing request via
    /// <c>HttpRequestMessage.Options</c>, so a delegating handler decides from metadata rather
    /// than by re-parsing the URL.
    /// </remarks>
    private GeneratedFile EmitOperations()
    {
        const string CloudPlatformScope = "https://www.googleapis.com/auth/cloud-platform";

        var writer = Header(RootNamespace, "Kkdev92.HealthData.Http");

        writer.XmlDoc("summary", "Descriptors for every operation in this API contract.");
        writer.XmlDoc(
            "remarks",
            "Attached to each outgoing request so that authorization, retry and diagnostics can " +
            "decide from metadata rather than by re-parsing the URL.");

        using (writer.Block("public static class HealthDataGeneratedOperations"))
        {
            var first = true;

            foreach (var operation in contract.Operations)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;

                var usesProjectCredentials = operation.Scopes.Count > 0 &&
                                             operation.Scopes.All(s => string.Equals(s, CloudPlatformScope, StringComparison.Ordinal));

                writer.XmlDoc("summary", $"Descriptor for {operation.Id}.");
                using (writer.Block(
                    $"public static readonly HealthDataOperationDescriptor {ResourceEmitter.DescriptorPropertyName(operation.Id)} = new()",
                    closing: "};"))
                {
                    writer.Line($"Id = {CodeWriter.Literal(operation.Id)},");
                    writer.Line($"ApiVersion = {CodeWriter.Literal(contract.ApiVersion)},");
                    writer.Line($"Method = HttpMethod.{MethodProperty(operation.HttpMethod)},");
                    writer.Line($"PathTemplate = {CodeWriter.Literal(operation.PathTemplate)},");
                    writer.Line($"Scopes = {Array(operation.Scopes)},");

                    // Emitted only where it is not the default, so a reader who sees this line
                    // knows the operation is the documented exception rather than boilerplate.
                    if (operation.ScopeCombination != ScopeCombination.AnyOf)
                    {
                        writer.Line(
                            "ScopeCombination = HealthDataScopeCombination."
                            + $"{operation.ScopeCombination},");
                    }

                    writer.Line($"RequiresProjectCredentials = {(usesProjectCredentials ? "true" : "false")},");
                    writer.Line($"RetryClassification = RetryClassification.{operation.RetryClassification},");
                    writer.Line($"ResponseKind = ResponseKind.{operation.ResponseKind},");
                    writer.Line($"Pagination = PaginationKind.{operation.Pagination?.Kind ?? PaginationKind.None},");
                }
            }

            writer.Line();
            writer.XmlDoc("summary", "Every descriptor, in operation id order.");
            writer.Line("public static readonly IReadOnlyList<HealthDataOperationDescriptor> All =");
            writer.Line("[");

            foreach (var operation in contract.Operations)
            {
                writer.Line($"    {ResourceEmitter.DescriptorPropertyName(operation.Id)},");
            }

            writer.Line("];");
        }

        return new GeneratedFile("Generated/Api/HealthDataGeneratedOperations.g.cs", writer.ToString());

        static string Array(IEnumerable<string> values)
        {
            var items = values.Select(CodeWriter.Literal).ToArray();
            return items.Length == 0 ? "[]" : "[" + string.Join(", ", items) + "]";
        }

        static string MethodProperty(string httpMethod) => httpMethod switch
        {
            "GET" => "Get",
            "POST" => "Post",
            "PATCH" => "Patch",
            "PUT" => "Put",
            "DELETE" => "Delete",
            _ => throw new InvalidOperationException($"Unsupported HTTP method '{httpMethod}'."),
        };
    }

    private GeneratedFile EmitModel(SchemaContract schema)
    {
        var usings = new List<string> { "System.Text.Json.Serialization" };

        if (schema.Properties.Any(p => Unwrap(p.Type).CSharpType.StartsWith("JsonElement", StringComparison.Ordinal)))
        {
            usings.Add("System.Text.Json");
        }

        if (schema.Properties.Any(p => p.Type.ConverterTypeName is not null))
        {
            usings.Add("Kkdev92.HealthData.Serialization");
        }

        var writer = Header(ModelsNamespace, [.. usings]);

        writer.XmlDoc("summary", schema.Description ?? schema.WireName);

        // A class, not a record: a generated ToString() would print health values.
        using (writer.Block($"public sealed partial class {schema.CSharpName}"))
        {
            var first = true;

            foreach (var property in schema.Properties)
            {
                if (!first)
                {
                    writer.Line();
                }

                first = false;

                writer.XmlDoc("summary", property.Description ?? property.WireName);

                // A cursor the service accepts and never returns. dailyRollUp takes a page token
                // like every other paged call and answers without a next one, so a loop written
                // the usual way either stops after one page or never stops at all. Saying so on
                // the property is the only place a caller is looking when they write that loop.
                if (CursorWithNoAnswer(schema, property))
                {
                    writer.XmlDoc(
                        "remarks",
                        "This operation accepts a cursor but returns none: its response carries no next page "
                        + "token. There is nothing to enumerate, which is why no streaming overload is "
                        + "generated for it.");
                }

                if (property.IsReadOnly)
                {
                    // ADR-0006: the property stays readable but the generated write contract
                    // removes it, so it is never transmitted.
                    writer.XmlDoc(
                        "remarks",
                        "Output only. This value is never sent to the service; it is removed from the write contract.");
                }

                writer.Line($"[JsonPropertyName({CodeWriter.Literal(property.WireName)})]");

                if (property.Type.ConverterTypeName is { } converter)
                {
                    writer.Line($"[JsonConverter(typeof({converter}))]");
                }

                writer.Line($"public {property.Type.CSharpType} {property.CSharpName} {{ get; init; }}");
            }

            if (_unions.TryGetValue(schema.WireName, out var union))
            {
                writer.Line();
                writer.XmlDoc("summary", "Members this contract does not know about.");

                // The consequence differs per union, so it is declared alongside the union in
                // semantics.json rather than written once here. One sentence about patching a
                // person's record, emitted onto a read-only roll-up, would be describing something
                // that cannot happen.
                writer.XmlDoc(
                    "remarks",
                    "The service may add a measurement after this contract was generated, and the "
                    + "deserializer has nowhere typed to put it. "
                    + (union.RoundTripNote is { Length: > 0 } note ? note + " " : string.Empty)
                    + "It is kept here instead and written out again with the same structure and "
                    + "the same values - though not necessarily the same bytes, since number "
                    + "formatting, string escapes and property order are the serializer's to "
                    + "choose. GetKind reports Unknown when this is the only thing set.");

                writer.Line("[JsonExtensionData]");

                // set rather than init: System.Text.Json refuses to bind extension data through an
                // init-only accessor on a type that has a deserialization constructor.
                writer.Line(
                    "public System.Collections.Generic.IDictionary<string, System.Text.Json.JsonElement>? "
                    + "ExtensionData { get; set; }");
            }

            EmitBodyPaging(writer, schema);
        }

        return new GeneratedFile($"Generated/Models/{schema.CSharpName}.g.cs", writer.ToString());
    }

    /// <summary>
    /// Whether a property is a paging cursor on an operation whose response returns no cursor.
    /// </summary>
    /// <remarks>
    /// Read from the pagination declaration rather than from the property's name: <c>pageToken</c>
    /// on a body that pages normally is not this, and the difference is the whole point.
    /// </remarks>
    private bool CursorWithNoAnswer(SchemaContract schema, PropertyContract property)
        => contract.Operations
            .Where(operation => operation.Pagination?.Kind == PaginationKind.RequestOnly)
            .Where(operation => operation.RequestSchema == schema.WireName)
            .Any(operation => operation.Pagination!.PageToken == property.WireName
                || operation.Pagination!.PageSize == property.WireName);

    /// <summary>
    /// Gives a request body that carries a cursor the copy its enumeration needs.
    /// </summary>
    /// <remarks>
    /// <para>
    /// One operation pages this way: <c>dataPoints.rollUp</c> puts <c>pageToken</c> in the body
    /// rather than the query. Its request could not be advanced a page without rebuilding the body
    /// by hand, so the streaming overload every other list operation gets was not generated for it
    /// and callers wrote the loop themselves.
    /// </para>
    /// <para>
    /// A copy method rather than making the model a record: a record's generated
    /// <c>ToString</c> would print a person's measurements, which is why models are classes at all.
    /// The generator knows every property, so the copy is exact without borrowing that.
    /// </para>
    /// </remarks>
    private void EmitBodyPaging(CodeWriter writer, SchemaContract schema)
    {
        var pagination = contract.Operations
            .Where(operation => operation.Pagination?.Kind == PaginationKind.Body)
            .Where(operation => operation.RequestSchema == schema.WireName)
            .Select(operation => operation.Pagination!)
            .FirstOrDefault();

        if (pagination?.PageToken is not { } pageToken)
        {
            return;
        }

        var tokenProperty = schema.Properties.Single(property => property.WireName == pageToken);

        writer.Line();
        writer.XmlDoc("summary", "Returns a copy of this body positioned at the given page.");
        writer.XmlDoc(
            "remarks",
            "This operation's cursor travels in the body, so advancing a page means a new body. "
            + "Everything but the page token is carried over unchanged.");

        using (writer.Block($"public {schema.CSharpName} WithPageToken(string? pageToken)"))
        {
            using (writer.Block("return new()", closing: "};"))
            {
                foreach (var property in schema.Properties)
                {
                    var value = property == tokenProperty ? "pageToken" : property.CSharpName;
                    writer.Line($"{property.CSharpName} = {value},");
                }
            }
        }
    }

    /// <summary>
    /// Emits every open enum a schema declares, nested inside that schema (ADR-0005).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Nested protobuf style: the enum for <c>Settings.distanceUnit</c> is
    /// <c>Settings.Types.DistanceUnit</c>, so the type is one guess away from the property a
    /// reader is looking at. It cannot be a direct member of the owner — a nested type may not
    /// share a name with the owner's property (CS0102) — which is exactly why protobuf's own C#
    /// codegen introduces the <c>Types</c> container, and following that convention means anyone
    /// who has consumed a Google API from C# has seen this shape before.
    /// </para>
    /// <para>
    /// The container is a partial of the model class, so the model file itself stays a plain list
    /// of properties.
    /// </para>
    /// </remarks>
    private GeneratedFile EmitOpenEnumContainer(IGrouping<string, OpenEnumContract> owner)
    {
        var ownerName = Normalization.NamingNormalizer.ToPascalCase(owner.Key);
        var writer = Header(ModelsNamespace, "System.Text.Json.Serialization", "Kkdev92.HealthData.Serialization");

        writer.XmlDoc("summary", $"The open enums declared inline on {owner.Key}.");
        using (writer.Block($"public sealed partial class {ownerName}"))
        {
            writer.XmlDoc(
                "summary",
                $"Container for {ownerName}'s nested types, following the protobuf C# convention.");
            using (writer.Block("public static class Types"))
            {
                var first = true;

                foreach (var openEnum in owner.OrderBy(e => e.CSharpName, StringComparer.Ordinal))
                {
                    if (!first)
                    {
                        writer.Line();
                    }

                    first = false;

                    // Everything inside the container refers to the enum by its leaf name; the
                    // scope resolves it, and the emitted file stays readable.
                    var leaf = Normalization.NamingNormalizer.ToPascalCase(openEnum.DeclaringProperty);

                    writer.XmlDoc("summary", $"Wire values for {openEnum.DeclaringSchema}.{openEnum.DeclaringProperty}.");
                    writer.XmlDoc(
                        "remarks",
                        "This is an open enum: values Google adds later are preserved verbatim rather than " +
                        "rejected. The members below are only those known when this contract was generated. " +
                        "It is not a C# enum - it is a struct wrapping the wire string, which is what lets an " +
                        "unknown value through - so Enum.TryParse and Enum.Parse do not work on it. They " +
                        "compile, because their constraint is only 'struct', and throw ArgumentException at " +
                        "run time. Use FromValue to build one from a string, and Value to read it back.");
                    writer.Line($"[JsonConverter(typeof(OpenStringEnumConverter<{leaf}>))]");

                    using (writer.Block(
                        $"public readonly partial record struct {leaf}(string Value) : IOpenStringValue<{leaf}>"))
                    {
                        writer.XmlDoc("summary", "Creates a value from its wire representation, known or not.");
                        writer.Line($"public static {leaf} FromValue(string value) => new(value);");

                        foreach (var value in openEnum.Values)
                        {
                            writer.Line();
                            // No inline markup here: XmlDoc escapes its input, so angle brackets
                            // would end up rendered literally as &lt;c&gt;.
                            writer.XmlDoc("summary", $"Wire value {value.WireValue}.");
                            writer.Line(
                                $"public static {leaf} {value.CSharpName} => new({CodeWriter.Literal(value.WireValue)});");
                        }

                        writer.Line();
                        writer.XmlDoc("summary", "Returns the wire value.");
                        writer.Line("public override string ToString() => Value;");
                    }
                }
            }
        }

        return new GeneratedFile($"Generated/Models/{ownerName}.Types.g.cs", writer.ToString());
    }

    /// <summary>
    /// Emits the source-generated serializer context covering every model.
    /// </summary>
    /// <remarks>
    /// Metadata mode is used explicitly. The fast path cannot deserialize at all and silently
    /// falls back whenever a custom converter is involved, which is most of this contract.
    /// </remarks>
    private GeneratedFile EmitJsonContext()
    {
        var writer = Header(RootNamespace + ".Serialization", "System.Text.Json.Serialization", ModelsNamespace);

        writer.XmlDoc("summary", "Source-generated serialization metadata for the Google Health API contract.");
        writer.XmlDoc(
            "remarks",
            "Reflection-based serialization is disabled for this assembly, so every type that " +
            "crosses the wire must appear here.");
        writer.Line("[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]");

        foreach (var schema in contract.Schemas)
        {
            writer.Line($"[JsonSerializable(typeof({schema.CSharpName}))]");
        }

        // The open enums are reachable through the schemas, so the serializer would register them
        // on its own - under a metadata property named after the type's simple name. Nesting made
        // the simple names collide: three owners declare a property called type, several declare
        // mealType, and the generator answers with SYSLIB1031. Each enum is therefore registered
        // explicitly, with the pre-nesting flat name as the metadata property name - unique by
        // construction, because it used to be the type name.
        foreach (var openEnum in contract.OpenEnums)
        {
            var flatName = Normalization.NamingNormalizer.ToPascalCase(openEnum.DeclaringSchema)
                + Normalization.NamingNormalizer.ToPascalCase(openEnum.DeclaringProperty);

            writer.Line(
                $"[JsonSerializable(typeof({openEnum.CSharpName}), TypeInfoPropertyName = {CodeWriter.Literal(flatName)})]");
            writer.Line(
                $"[JsonSerializable(typeof({openEnum.CSharpName}?), TypeInfoPropertyName = {CodeWriter.Literal("Nullable" + flatName)})]");
        }

        writer.Line("public sealed partial class HealthDataJsonContext : JsonSerializerContext;");

        return new GeneratedFile("Generated/Serialization/HealthDataJsonContext.g.cs", writer.ToString());
    }

    /// <summary>
    /// Emits the table of output-only properties used to build the write contract (ADR-0006).
    /// </summary>
    /// <remarks>
    /// Keyed by wire name, because that is what <c>JsonPropertyInfo.Name</c> reports once the
    /// contract is built.
    /// </remarks>
    private GeneratedFile EmitOutputOnlyProperties()
    {
        var writer = Header(RootNamespace + ".Serialization", ModelsNamespace);

        var withReadOnly = contract.Schemas
            .Where(s => s.Properties.Any(p => p.IsReadOnly))
            .ToArray();

        writer.XmlDoc("summary", "Properties Discovery marks readOnly, which must never be transmitted.");
        writer.XmlDoc(
            "remarks",
            "Used to remove these properties from the write contract. They remain readable on the " +
            "model; only serialization drops them (ADR-0006).");

        using (writer.Block("public static class HealthDataOutputOnlyProperties"))
        {
            writer.XmlDoc("summary", "Wire property names that are output only, keyed by model type.");

            using (writer.Block(
                "public static readonly IReadOnlyDictionary<Type, string[]> ByType = new Dictionary<Type, string[]>",
                closing: "};"))
            {
                foreach (var schema in withReadOnly)
                {
                    var names = schema.Properties
                        .Where(p => p.IsReadOnly)
                        .Select(p => CodeWriter.Literal(p.WireName));

                    writer.Line($"[typeof({schema.CSharpName})] = [{string.Join(", ", names)}],");
                }
            }
        }

        return new GeneratedFile("Generated/Serialization/HealthDataOutputOnlyProperties.g.cs", writer.ToString());
    }

    /// <summary>
    /// Emits the data type table, which Discovery does not carry.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The generator has always read <c>data-types.json</c> and used none of it, so a consumer
    /// needing "does steps support get" had to copy the table into their own application — which
    /// one did, from this repository, with a comment saying it had nowhere else to get it.
    /// </para>
    /// <para>
    /// <strong>Metadata, not validation.</strong> The snapshot says capabilities "must not become
    /// client-side hard validation; the server remains the authority", so nothing in the SDK reads
    /// this before sending. It answers a question; it does not stop a request.
    /// </para>
    /// <para>
    /// <c>FilterName</c> is published and filter expressions are not built from it. The table has
    /// the member's prefix and no more: <c>heart-rate</c> filters on
    /// <c>heart_rate.sample_time.physical_time</c> while <c>steps</c> filters on
    /// <c>steps.interval.start_time</c>, and three types reject the interval member the others
    /// accept. Composing an expression from the prefix would produce a 400 that looks like the
    /// SDK's own answer.
    /// </para>
    /// </remarks>
    private GeneratedFile EmitDataTypes()
    {
        var writer = Header(RootNamespace);

        writer.XmlDoc("summary", "A data type, and the operations Google documents for it.");
        writer.XmlDoc(
            "remarks",
            "Metadata only. The service is the authority on what a type supports; this is what its "
            + "own documentation says, captured when the contract was generated.");

        using (writer.Block("public sealed record HealthDataDataTypeDescriptor"))
        {
            writer.XmlDoc("summary", "The kebab-case id used in a resource name, for example `heart-rate`.");
            writer.Line("public required string Id { get; init; }");
            writer.Line();

            writer.XmlDoc("summary", "The snake_case name a filter is written against, for example `heart_rate`.");
            writer.XmlDoc(
                "remarks",
                "A different string from the id and not derivable from it - both are preserved "
                + "verbatim. It is the prefix of a filter member, not a filter: the rest of the path "
                + "differs per type, and some types accept no filter at all. Build an expression "
                + "from what the service documents for the type, not from this.");
            writer.Line("public required string FilterName { get; init; }");
            writer.Line();

            writer.XmlDoc("summary", "The operation short names documented for this type, for example `list`.");
            writer.Line("public required IReadOnlyList<string> Operations { get; init; }");
            writer.Line();

            writer.XmlDoc("summary", "Whether the documentation lists an operation for this type.");
            writer.XmlDoc(
                "remarks",
                "Worth asking before offering a button, and not worth refusing a request over: a "
                + "type that gained an operation after this contract was generated answers false "
                + "here and succeeds at the service.");
            writer.Line("public bool Supports(string operation)");
            writer.Line("    => Operations.Contains(operation, StringComparer.Ordinal);");
        }

        writer.Line();
        writer.XmlDoc("summary", "The data types the Google Health API documents.");
        writer.XmlDoc(
            "remarks",
            "Captured from https://developers.google.com/health/data-types, which is the only place "
            + "this appears: the REST path is the generic dataTypes/{dataTypesId}, so Discovery says "
            + "nothing about what any individual type supports.");

        using (writer.Block("public static class HealthDataGeneratedDataTypes"))
        {
            writer.XmlDoc("summary", "Every documented data type, ordered by id.");
            writer.Line("public static IReadOnlyList<HealthDataDataTypeDescriptor> All { get; } =");
            writer.Line("[");

            foreach (var dataType in contract.DataTypes)
            {
                var operations = string.Join(", ", dataType.Operations.Select(CodeWriter.Literal));

                writer.Line("    new()");
                writer.Line("    {");
                writer.Line($"        Id = {CodeWriter.Literal(dataType.Id)},");
                writer.Line($"        FilterName = {CodeWriter.Literal(dataType.FilterName)},");
                writer.Line($"        Operations = [{operations}],");
                writer.Line("    },");
            }

            writer.Line("];");
            writer.Line();

            writer.XmlDoc("summary", "The descriptor for an id, or null when the id is not documented here.");
            writer.XmlDoc(
                "remarks",
                "Null is not the same as unsupported. A type Google adds after this contract was "
                + "generated is absent from the table and works perfectly well at the service.");
            writer.Line("public static HealthDataDataTypeDescriptor? Find(string id)");
            writer.Line("    => All.FirstOrDefault(dataType => string.Equals(dataType.Id, id, StringComparison.Ordinal));");
        }

        return new GeneratedFile("Generated/Api/HealthDataGeneratedDataTypes.g.cs", writer.ToString());
    }

    /// <summary>
    /// Emits the alternatives of each union, for the check that runs before a request is written.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The same member list <c>GetKind</c> is generated from, in a form the serializer can read.
    /// Discovery cannot say "exactly one of these", so nothing in the type system stops two being
    /// set; the service refuses it and says which operation failed rather than which pair did.
    /// </para>
    /// <para>
    /// Wire names, because that is what the write contract's properties are keyed by, and what the
    /// message should quote — a caller reading it is about to go and look at the JSON.
    /// </para>
    /// </remarks>
    private GeneratedFile EmitUnionMembers()
    {
        var writer = Header(RootNamespace + ".Serialization", ModelsNamespace);

        writer.XmlDoc("summary", "The mutually exclusive members of each union schema, keyed by model type.");
        writer.XmlDoc(
            "remarks",
            "Used to refuse a request that sets two of them. Members that are not alternatives - "
            + "dataSource, which every measurement carries - are not listed, exactly as they are "
            + "left out of GetKind.");

        using (writer.Block("public static class HealthDataUnionMembers"))
        {
            writer.XmlDoc("summary", "Wire property names that are alternatives, keyed by model type.");

            using (writer.Block(
                "public static readonly IReadOnlyDictionary<Type, string[]> ByType = new Dictionary<Type, string[]>",
                closing: "};"))
            {
                foreach (var (unionSchema, declared) in _unions.OrderBy(u => u.Key, StringComparer.Ordinal))
                {
                    if (contract.Schemas.SingleOrDefault(s => s.WireName == unionSchema) is not { } schema)
                    {
                        continue;
                    }

                    var names = schema.Properties
                        .Where(p => p.Type.Kind == TypeKind.Reference)
                        .Where(p => !declared.ExcludedMembers.Contains(p.WireName))
                        .Select(p => CodeWriter.Literal(p.WireName));

                    writer.Line($"[typeof({schema.CSharpName})] = [{string.Join(", ", names)}],");
                }
            }
        }

        return new GeneratedFile("Generated/Serialization/HealthDataUnionMembers.g.cs", writer.ToString());
    }

    /// <summary>
    /// Emits discovery helpers for a union-shaped schema.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>DataPoint</c> is a name plus 42 mutually exclusive measurement members, and
    /// <c>RollupDataPoint</c> is the same shape with 21. Working with that as bare nullable
    /// properties means writing a 42-arm if-chain at every call site. These helpers give the
    /// caller the populated member without collapsing the union into <c>object</c>.
    /// </para>
    /// <para>
    /// Not every message-typed property is an alternative. <c>DataPoint.dataSource</c> records
    /// which device or app produced the measurement and is present alongside it, so counting it
    /// as a member made <c>GetKind</c> answer <c>DataSource</c> for everything the service
    /// actually returns. Which ones to leave out is declared in <c>semantics.json</c>, never
    /// inferred from the schema, because the schema does not say.
    /// </para>
    /// </remarks>
    private GeneratedFile EmitUnionHelpers(SchemaContract schema, IReadOnlySet<string> excludedMembers)
    {
        var members = schema.Properties
            .Where(p => p.Type.Kind == TypeKind.Reference)
            .Where(p => !excludedMembers.Contains(p.WireName))
            .ToArray();

        var kindEnum = $"{schema.CSharpName}Kind";
        var writer = Header(ModelsNamespace);

        writer.XmlDoc("summary", $"Which member of a {schema.CSharpName} carries a value.");
        writer.XmlDoc(
            "remarks",
            "Unknown means the service sent a member added after this contract was generated. " +
            "That is not an error: the payload still round-trips, it simply has no typed accessor here.");

        using (writer.Block($"public enum {kindEnum}"))
        {
            writer.XmlDoc("summary", "No measurement member was set.");
            writer.Line("None,");
            writer.Line();
            writer.XmlDoc("summary", "A member this contract does not know about was set.");
            writer.Line("Unknown,");

            foreach (var member in members)
            {
                writer.Line();
                writer.XmlDoc("summary", $"The {member.WireName} member.");
                writer.Line($"{member.CSharpName},");
            }
        }

        writer.Line();
        writer.XmlDoc("summary", $"Convenience accessors over the {schema.CSharpName} union.");

        using (writer.Block($"public static class {schema.CSharpName}Extensions"))
        {
            writer.XmlDoc("summary", "Returns which member carries a value.");
            writer.XmlDoc("param name=\"value\"", $"The {schema.CSharpName}.");

            using (writer.Block($"public static {kindEnum} GetKind(this {schema.CSharpName} value)"))
            {
                writer.Line("ArgumentNullException.ThrowIfNull(value);");
                writer.Line();

                var first = true;

                foreach (var member in members)
                {
                    using (writer.Block($"{(first ? "if" : "else if")} (value.{member.CSharpName} is not null)"))
                    {
                        writer.Line($"return {kindEnum}.{member.CSharpName};");
                    }

                    first = false;
                }

                writer.Line();
                writer.Line("// Unknown rather than None when the payload carried a member this contract has");
                writer.Line("// never heard of: nothing typed to hand back, but not nothing there.");

                using (writer.Block("if (value.ExtensionData is { Count: > 0 })"))
                {
                    writer.Line($"return {kindEnum}.Unknown;");
                }

                writer.Line();
                writer.Line($"return {kindEnum}.None;");
            }

            writer.Line();
            writer.XmlDoc("summary", "Returns the populated member, or null when none is set.");
            writer.XmlDoc(
                "remarks",
                "The declared return type is object because the union members share no base type. " +
                "Prefer GetKind with a switch, or the typed properties directly, when the member " +
                "is known.");
            writer.XmlDoc("param name=\"value\"", $"The {schema.CSharpName}.");

            using (writer.Block($"public static object? GetValue(this {schema.CSharpName} value)"))
            {
                writer.Line("ArgumentNullException.ThrowIfNull(value);");
                writer.Line();
                writer.Line("return");
                var first = true;

                foreach (var member in members)
                {
                    writer.Line($"    {(first ? " " : "?? ")}(object?)value.{member.CSharpName}");
                    first = false;
                }

                writer.Line("    ;");
            }
        }

        return new GeneratedFile($"Generated/Models/{schema.CSharpName}Extensions.g.cs", writer.ToString());
    }

    private static TypeContract Unwrap(TypeContract type)
        => type.Kind == TypeKind.Array && type.ElementType is not null ? type.ElementType : type;
}
