<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Kkdev92.HealthData.Webhooks/Kkdev92.HealthData.Webhooks.csproj" />
    <ProjectReference Include="../Kkdev92.HealthData.TestSupport/Kkdev92.HealthData.TestSupport.csproj" />
  </ItemGroup>

</Project>
